# Generated by Django 3.1 on 2020-08-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb_image',
            field=models.ImageField(blank=True, default='/posts/default.jpg', upload_to='media/posts/'),
        ),
    ]
