# Generated by Django 3.1 on 2020-08-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_thumb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default='Description...', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Title...', max_length=40),
        ),
    ]
